Format: 1A
HOST: http://localhost:8080

# Hello World

You know what this does.

# Data Structures

## Message
+ time: `2015-11-11T08:40:51.620Z` (string)
+ msg: Hello World (string)

# Hello [/hi]

## Say Hello [GET]
+ Response 200 (application/json)
    + Attributes (Message)
